version: '2'
services:
    sparkwebshell-app:
        image: sparkwebshell
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sparkwebshell-mysql:3306/sparkwebshell?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sparkwebshell-mysql:
        extends:
            file: mysql.yml
            service: sparkwebshell-mysql
